import { z } from 'zod';
export declare const ServerConfigSchema: any;
export declare const ModelConfigSchema: any;
export declare const FeishuConfigSchema: any;
export declare const SlackConfigSchema: any;
export declare const PluginConfigSchema: any;
export declare const ConfigSchema: any;
export type Config = z.infer<typeof ConfigSchema>;
export type ServerConfig = z.infer<typeof ServerConfigSchema>;
export type ModelConfig = z.infer<typeof ModelConfigSchema>;
export type FeishuConfig = z.infer<typeof FeishuConfigSchema>;
export type SlackConfig = z.infer<typeof SlackConfigSchema>;
